name: nca

services:
  rdbms:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=openoni
      - MYSQL_USER=openoni
      - MYSQL_PASSWORD=openoni
    volumes:
      - data-mariadb:/var/lib/mysql

  solr:
    image: solr:8-slim
    volumes:
      - data-solr:/var/solr
    command:
      - solr-precreate
      - openoni

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-oni
      target: oni
    volumes:
      - oni-batches:/mnt/batches
    depends_on:
      - rdbms
      - solr
      - rais
      - agent
    environment:
      - APACHE_LOG_LEVEL=info
      - ONI_DEBUG=1
      - ONI_BASE_URL=http://localhost:8080
      - ONI_IIIF_URL=http://localhost:8080/images/iiif

  rais:
    image: uolibraries/rais:4-alpine
    environment:
      - RAIS_IIIFWEBPATH=/images/iiif
      - RAIS_IIIFBASEURL=http://localhost:8080
      - RAIS_TILECACHELEN=250
      - RAIS_TILEPATH=/mnt/batches
    volumes:
      - oni-batches:/mnt/batches

  agent:
    build:
      dockerfile: ./docker/Dockerfile-oni
      target: agent
    volumes:
      - oni-batches:/mnt/batches
      - agent-rsa:/etc/rsa/
    depends_on:
      - rdbms
      - solr
    environment:
      - BA_BIND=:22
      - HOST_KEY_FILE=/etc/rsa/oni-agent
      - ONI_LOCATION=/opt/openoni/
      - BATCH_SOURCE=/mnt/batches/
      - DB_CONNECTION=openoni:openoni@tcp(rdbms:3306)/openoni
    expose:
      - 22

volumes:
  oni-batches:
  data-mariadb:
  data-solr:
  agent-rsa:
